# Generated by Django 2.2.5 on 2021-04-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20210410_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='amenity',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
