# Generated by Django 2.2.5 on 2021-04-18 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_amenity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='amenity',
        ),
    ]
